name: wallpaper_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.2
  intl: ^0.16.1
  flutter_downloader: ^1.5.2
  font_awesome_flutter: ^9.1.0
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_staggered_grid_view: ^0.4.0
  shared_preferences: ^2.0.6
  cached_network_image: ^3.1.0
  launch_review: ^3.0.1
  shimmer: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  bottom_navy_bar: ^5.6.0
  material_design_icons_flutter: ^4.0.5955
  anim_search_bar: ^2.0.2
  smooth_page_indicator: ^0.2.3
  filter_list: ^1.0.0
  image_downloader: ^0.30.0
  wallpaper_manager: ^1.0.10
  flutter_cache_manager: ^3.1.2
  dio: ^4.0.0
  sqflite: ^2.0.0+3
  pull_to_refresh: ^2.0.0
  dynamic_themes: ^1.1.0

  # material_floating_search_bar: ^0.3.4
  #google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assests/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    
    - family: Raleway
      fonts:
        - asset: assests/Raleway-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assests/Montserrat-Bold.ttf
    - family: MontserratSemi
      fonts:
        - asset: assests/Montserrat-SemiBold.ttf  
    - family: Pacifico
      fonts:
        - asset: assests/Pacifico-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assests/Roboto-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assests/Poppins-SemiBold.ttf    
    - family: RalewayTwo
      fonts:
        - asset: assests/Raleway-Bold.ttf
    - family: RalewayExtra
      fonts:
        - asset: assests/Raleway-ExtraBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
